# ----
# Site
title: witzelphotos
baseurl: ""
url: https://witzelphotos.dk
enforce_ssl: witzelphotos.dk
google_analytics_key: UA-109612259-1

# Values for the jekyll-seo-tag gem (https://github.com/jekyll/jekyll-seo-tag)
logo: /facico.ico
description: Fotograf på fyn, gode billeder til billige penge.
author:
  name: William Witzel
  email: Witzeltwo@gmail.com
  twitter: WitzelPhotos
social:
  name: WitzelPhotos
  links:
    - https://github.com/williamwitzel
    