# ----
# Site
title: witzelphotos
baseurl: ""
url: https://witzelphotos.dk
enforce_ssl: witzelphotos.dk
google_analytics_key: UA-109612259-1

# Values for the jekyll-seo-tag gem (https://github.com/jekyll/jekyll-seo-tag)
logo: /facico.ico
description: Fotograf på fyn, gode billeder til billige penge.
author:
  name: William Witzel
  email: Witzeltwo@gmail.com
  twitter: WitzelPhotos
social:
  name: WitzelPhotos
  links:
    - https://github.com/williamwitzel
    
# -----
# Build

permalink: /:categories/:title/

gems:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-archives

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENCE

collections:
  sets:


jekyll-archives:
  enabled: ['catagories']

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      type: "posts"
    values:
      layout: "post"
      comments: true
  -
    scope:
      type: "sets"
    values:
      _hide_content: true
  -
    scope:
      path: "index.html"
    values:
      body_class: "show_hero_search"